[tools]

# Go Packages
"go:github.com/spf13/cobra-cli" = "latest"
"go:golang.org/x/tools/cmd/goimports" = "latest"
"go:github.com/vektra/mockery/v2" = "latest"
"go:github.com/goreleaser/chglog/cmd/chglog" = "latest"
"go:golang.org/x/vuln/cmd/govulncheck" = "latest"

go = "1.25.7"
trivy = "latest"
syft = "latest"
markdownlint-cli2 = "0.18.1"
yamlfmt = "0.20.0"
yamllint = "1.37.1"
yq = "4.48.1"
prettier = "3.7.4"
golines = "latest"
