---
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDashboard
metadata:
  name: zfs-status-dashboard
  namespace: monitoring
spec:
  allowCrossNamespaceImport: true
  instanceSelector:
    matchLabels:
      app: grafana
  folder: Infrastructure
  configMapRef:
    name: zfs-status-dashboard
    key: zfs-status.json
  datasources:
    - inputName: DS_PROMETHEUS
      datasourceName: Prometheus
