---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # generated PrometheusRule CRs (run `make dashboards` to regenerate)
  - data/zfs-recording-rules.yaml
  - data/zfs-alerts.yaml
  # scrape-configs
  - scrape-configs/zfs.yaml
